# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Sat Nov 29 17:42:03 2025
#

import wx




class _924705493_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((485, 506))
        self.SetTitle("Compra Y Costo")

        self.panel_1 = wx.Panel(self, -1)
        self.panel_1.SetBackgroundColour(wx.Colour(151, 5, 14))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("D:\\CineMoviev4\\imagencodigodebarras.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((160, 230))
        grid_sizer_3.Add(bitmap_1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(8, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, -1, "Compra y Costo")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Lucida Sans Unicode"))
        grid_sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_2 = wx.StaticText(self.panel_1, -1, "Cine Movie")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Lucida Sans Unicode"))
        grid_sizer_4.Add(label_2, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, -1, "Pelicula:")
        label_3.SetMinSize((80, 24))
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_5.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, -1, "-----")
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_5.Add(label_4, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, -1, "Dulceria:")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_6.Add(label_5, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, -1, "--------")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_6.Add(label_6, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, -1, "Fecha:")
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        label_7.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_7.Add(label_7, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, -1, "----")
        label_8.SetForegroundColour(wx.Colour(255, 255, 255))
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_7.Add(label_8, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, -1, "Hora:")
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_8.Add(label_9, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, -1, "----")
        label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        label_10.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_8.Add(label_10, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.panel_1, -1, "Subtotal:")
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_9.Add(label_11, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, -1, "------")
        label_12.SetForegroundColour(wx.Colour(255, 255, 255))
        label_12.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_9.Add(label_12, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, -1, "Total:")
        label_13.SetForegroundColour(wx.Colour(255, 255, 255))
        label_13.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_10.Add(label_13, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, -1, "---")
        label_14.SetForegroundColour(wx.Colour(255, 255, 255))
        label_14.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_10.Add(label_14, 0, 0, 0)

        self.btnAceptar = wx.Button(self.panel_1, -1, "Aceptar")
        grid_sizer_10.Add(self.btnAceptar, 0, 0, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

