#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat Nov 29 17:49:21 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana4(wx.Frame):
    def __init__(self, parent, informacion="", subtotal1=0, informacion2="", subtotal2=0):
        # begin wxGlade: Ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((485, 506))
        self.SetTitle("Compra Y Costo")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(151, 5, 14))

        #Variables de instancia de la ventana 4
        self.infoTaquilla=informacion
        self.infoDulceria=informacion2
        self.subtotalTaquilla=subtotal1
        self.subtotalDulceria=subtotal2
        self.total=self.subtotalTaquilla+self.subtotalDulceria

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./imagencodigodebarras.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((160, 230))
        grid_sizer_3.Add(bitmap_1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(8, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Compra y Costo")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Lucida Sans Unicode"))
        grid_sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cine Movie")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Lucida Sans Unicode"))
        grid_sizer_4.Add(label_2, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, f"Taquilla")
        label_3.SetMinSize((80, 24))
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_5.Add(label_3, 0, 0, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        lbPelicula.SetForegroundColour(wx.Colour(255, 255, 255))
        lbPelicula.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_5.Add(lbPelicula, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_6.Add(label_5, 0, 0, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}")
        lbDulceria.SetForegroundColour(wx.Colour(255, 255, 255))
        lbDulceria.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_6.Add(lbDulceria, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        label_7.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_7.Add(label_7, 0, 0, 0)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        lbSala.SetForegroundColour(wx.Colour(255, 255, 255))
        lbSala.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_7.Add(lbSala, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria:")
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_8.Add(label_9, 0, 0, 0)

        lbhorario = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}")
        lbhorario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbhorario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_8.Add(lbhorario, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_9.Add(label_11, 0, 0, 0)

        lbsubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.subtotalTaquilla, self.subtotalDulceria}")
        lbsubtotal.SetForegroundColour(wx.Colour(255, 255, 255))
        lbsubtotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_9.Add(lbsubtotal, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Total:")
        label_13.SetForegroundColour(wx.Colour(255, 255, 255))
        label_13.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_10.Add(label_13, 0, 0, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.total}")
        lbTotal.SetForegroundColour(wx.Colour(255, 255, 255))
        lbTotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Lucida Sans Unicode"))
        grid_sizer_10.Add(lbTotal, 0, 0, 0)

        self.btnAceptar = wx.Button(self.panel_1, wx.ID_ANY, "Aceptar")
        grid_sizer_10.Add(self.btnAceptar, 0, 0, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        wx.Exit()
        event.Skip()

# end of class Ventana4

class MyAppCineMovie(wx.App):
    def OnInit(self):
        self.frame = Ventana4(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCineMovie

if __name__ == "__main__":
    appCineMovie = MyAppCineMovie(0)
    appCineMovie.MainLoop()
