#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Nov 28 13:21:41 2025
#

import wx
#Siguiente ventana
from cinemoviev4 import Ventana4

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal1=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((932, 788))
        self.SetTitle("DulceriaCineMovie")
        print(f"Datos de la ventana2 \n Informacion{informacion} \n ")
        print(f"Subtotal: {subtotal1}")


        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(149, 0, 9))

        #Variables de instancia de la ventana 3
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal1

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 6, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Precio")
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Contenido")
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Imagen")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2 = wx.GridSizer(1, 5, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_2.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "$150")
        label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        label_10.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_2.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas\n       +\nRefresco")
        label_14.SetMinSize((90, 67))
        label_14.SetForegroundColour(wx.Colour(255, 255, 255))
        label_14.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Calisto MT"))
        grid_sizer_2.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Palomitas+Refresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_1, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_8.Add(self.spComboB, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_3 = wx.GridSizer(1, 7, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pareja")
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_3.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "$328")
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_3.Add(label_11, 0, wx.ALIGN_CENTER, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Ramen\n    +\nICEE\n    +\nHelado")
        label_15.SetForegroundColour(wx.Colour(255, 255, 255))
        label_15.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Calisto MT"))
        grid_sizer_3.Add(label_15, 0, 0, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Ramen.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_2, 0, wx.ALIGN_CENTER, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./ICEE.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_3, 0, wx.ALIGN_CENTER, 0)

        bitmap_8 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Helado.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_8, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_9 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.spComboP = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_9.Add(self.spComboP, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(1, 7, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar")
        label_8.SetForegroundColour(wx.Colour(255, 255, 255))
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_4.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "$320")
        label_12.SetForegroundColour(wx.Colour(255, 255, 255))
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_4.Add(label_12, 0, wx.ALIGN_CENTER, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "PizzaFam\n      +\nRefresco2L\n      +\nAlitasBBQ")
        label_16.SetForegroundColour(wx.Colour(255, 255, 255))
        label_16.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Calisto MT"))
        grid_sizer_4.Add(label_16, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Pizza.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(bitmap_5, 0, wx.ALIGN_CENTER, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./CocaCola2L.png", wx.BITMAP_TYPE_ANY))
        bitmap_6.SetMinSize((70, 90))
        grid_sizer_4.Add(bitmap_6, 0, wx.ALIGN_CENTER, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Alitas BBQ.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(bitmap_7, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_10 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spComboF, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.GridSizer(1, 7, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Extra Yumi")
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_5.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "$180")
        label_13.SetForegroundColour(wx.Colour(255, 255, 255))
        label_13.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_5.Add(label_13, 0, wx.ALIGN_CENTER, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "2Rebanadas de Pastel\n              +\n2Frapuchinos")
        label_17.SetForegroundColour(wx.Colour(255, 255, 255))
        label_17.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Calisto MT"))
        grid_sizer_5.Add(label_17, 0, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Pastel1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(bitmap_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        bitmap_11 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Pastel2.png", wx.BITMAP_TYPE_ANY))
        bitmap_11.SetMinSize((80, 80))
        grid_sizer_6.Add(bitmap_11, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        bitmap_12 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Frapuchino1.png", wx.BITMAP_TYPE_ANY))
        bitmap_12.SetMinSize((45, 70))
        grid_sizer_7.Add(bitmap_12, 0, wx.ALIGN_CENTER, 0)

        bitmap_13 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Frapuchino2.png", wx.BITMAP_TYPE_ANY))
        bitmap_13.SetMinSize((45, 70))
        grid_sizer_7.Add(bitmap_13, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_11 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.spComboY = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_11.Add(self.spComboY, 0, wx.ALIGN_CENTER, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Individuales:")
        label_19.SetForegroundColour(wx.Colour(255, 255, 255))
        label_19.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        sizer_1.Add(label_19, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_12 = wx.GridSizer(2, 6, 0, 0)
        sizer_1.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "1) Palomitas")
        label_20.SetForegroundColour(wx.Colour(255, 255, 255))
        label_20.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_12.Add(label_20, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_13 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.spCantidadPalomitas = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidadPalomitas.SetMinSize((66, 23))
        self.spCantidadPalomitas.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_13.Add(self.spCantidadPalomitas, 0, wx.ALIGN_CENTER, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "2) ICEE")
        label_21.SetForegroundColour(wx.Colour(255, 255, 255))
        label_21.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_12.Add(label_21, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_14 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        self.spCantidadICEE = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidadICEE.SetMinSize((66, 23))
        self.spCantidadICEE.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_14.Add(self.spCantidadICEE, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_15 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        bitmap_9 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./PalomitasIndv.png", wx.BITMAP_TYPE_ANY))
        bitmap_9.SetMinSize((55, 55))
        grid_sizer_15.Add(bitmap_9, 0, wx.EXPAND, 0)

        grid_sizer_16 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        bitmap_10 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./ICEEIndv.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_16.Add(bitmap_10, 0, wx.EXPAND, 0)

        self.cmbTamanoPalomitas = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Grandes", "Medianas", "Chicas"], style=wx.CB_DROPDOWN)
        self.cmbTamanoPalomitas.SetMinSize((66, 23))
        self.cmbTamanoPalomitas.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_12.Add(self.cmbTamanoPalomitas, 0, wx.ALIGN_CENTER, 0)

        self.btnAgregarP = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        grid_sizer_12.Add(self.btnAgregarP, 0, wx.ALIGN_CENTER, 0)

        self.cmbTamanoICEE = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Grande", "Mediano", "Chico"], style=wx.CB_DROPDOWN)
        self.cmbTamanoICEE.SetMinSize((66, 23))
        self.cmbTamanoICEE.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_12.Add(self.cmbTamanoICEE, 0, wx.ALIGN_CENTER, 0)

        self.btnAgrgarI = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        grid_sizer_12.Add(self.btnAgrgarI, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_23 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_23.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_12.Add(self.panel_3, 1, wx.EXPAND, 0)

        grid_sizer_17 = wx.GridSizer(2, 6, 0, 0)
        sizer_1.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "3) Refresco")
        label_22.SetForegroundColour(wx.Colour(255, 255, 255))
        label_22.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_17.Add(label_22, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_18 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        self.spCantidadRefresco = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidadRefresco.SetMinSize((66, 23))
        self.spCantidadRefresco.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_18.Add(self.spCantidadRefresco, 0, wx.ALIGN_CENTER, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "4) Helado")
        label_23.SetForegroundColour(wx.Colour(255, 255, 255))
        label_23.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_17.Add(label_23, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_19 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_19, 1, wx.ALIGN_CENTER, 0)

        self.spCantidadHelado = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidadHelado.SetMinSize((66, 23))
        self.spCantidadHelado.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_19.Add(self.spCantidadHelado, 0, 0, 0)

        grid_sizer_20 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        bitmap_14 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./CocaColaIndv.png", wx.BITMAP_TYPE_ANY))
        bitmap_14.SetMinSize((55, 55))
        grid_sizer_20.Add(bitmap_14, 0, wx.EXPAND, 0)

        grid_sizer_21 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        bitmap_15 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./HeladoIndv.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_21.Add(bitmap_15, 0, wx.ALIGN_CENTER, 0)

        self.cmbsaborRefresco = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Fanta", "Pepsi", "Sprite", "CocaCola"], style=wx.CB_DROPDOWN)
        self.cmbsaborRefresco.SetMinSize((66, 23))
        grid_sizer_17.Add(self.cmbsaborRefresco, 0, wx.ALIGN_CENTER, 0)

        self.btnAgregarR = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        grid_sizer_17.Add(self.btnAgregarR, 0, wx.ALIGN_CENTER, 0)

        self.cmbSaborHelado = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Chocochips", "Chocolate", "Quesoconsarzamora", "Picafresa"], style=wx.CB_DROPDOWN)
        self.cmbSaborHelado.SetMinSize((66, 23))
        grid_sizer_17.Add(self.cmbSaborHelado, 0, wx.ALIGN_CENTER, 0)

        self.btnAgregarH = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        grid_sizer_17.Add(self.btnAgregarH, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_24 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_17.Add(grid_sizer_24, 1, wx.EXPAND, 0)

        label_27 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        label_27.SetForegroundColour(wx.Colour(100, 171, 255))
        label_27.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Noto Sans Cond"))
        grid_sizer_24.Add(label_27, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$---")
        self.lbSubtotal.SetForegroundColour(wx.Colour(255, 244, 0))
        self.lbSubtotal.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_24.Add(self.lbSubtotal, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_25 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_17.Add(grid_sizer_25, 1, wx.EXPAND, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos\nAgregados:")
        label_25.SetForegroundColour(wx.Colour(100, 171, 255))
        label_25.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Noto Sans Cond"))
        grid_sizer_25.Add(label_25, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "- - -")
        self.lbProductosAgregados.SetForegroundColour(wx.Colour(249, 255, 0))
        self.lbProductosAgregados.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_25.Add(self.lbProductosAgregados, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_22 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((112, 56))
        self.btnLimpiar.SetBitmap(wx.Bitmap("LogoVolver.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_22.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((112, 56))
        self.btnSiguiente.SetBitmap(wx.Bitmap("ImagenSiguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_22.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((112, 56))
        self.btnSalir.SetBitmap(wx.Bitmap("LogoSalida.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_22.Add(self.btnSalir, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboP.Bind(wx.EVT_SPINCTRL, self.calcularComboPareja)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spComboY.Bind(wx.EVT_SPINCTRL, self.calcularComboYumi)
        self.btnAgregarP.Bind(wx.EVT_BUTTON, self.agregarPalomitas)
        self.btnAgrgarI.Bind(wx.EVT_BUTTON, self.agregarICEE)
        self.btnAgregarR.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnAgregarH.Bind(wx.EVT_BUTTON, self.agregarHelado)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.LimpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrarDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombob=numero*150
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombob
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboPareja(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboP.GetValue())
        subtotalcombop=numero*328
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombop
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Pareja \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombof=numero*320
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombof
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboYumi(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboY.GetValue())
        subtotalcomboy=numero*180
        self.subtotalDulceria=self.subtotalDulceria+subtotalcomboy
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Yumi \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarPalomitas(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidadPalomitas.GetValue())
        tamanyo=self.cmbTamanoPalomitas.GetValue()
        if tamanyo == "Chicas":
            subtotalpalomitas=numero*25
        elif tamanyo == "Medianas":
            subtotalpalomitas=numero*40
        elif tamanyo == "Grandes":
            subtotalpalomitas=numero*60
        
        self.subtotalDulceria=self.subtotalDulceria+subtotalpalomitas
        self.lbSubtotal.SetLabel(f"$ {self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero}  Palomitas: tamaño {tamanyo} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarICEE(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidadICEE.GetValue())
        tamanyo=self.cmbTamanoICEE.GetValue()
        if tamanyo == "Grande":
            subtotalice=numero*70
        elif tamanyo == "Mediano":
            subtotalice=numero*55
        elif tamanyo == "Chico":
            subtotalice=numero*45
        
        self.subtotalDulceria=self.subtotalDulceria+subtotalice
        self.lbSubtotal.SetLabel(f"$ {self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero}  ICE: tamaño {tamanyo} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidadRefresco.GetValue())
        sabor=self.cmbsaborRefresco.GetValue()
        if sabor == "Fanta":
            subtotalrefresco=numero*30
        elif sabor == "Pepsi":
            subtotalrefresco=numero*35
        elif  sabor == "Sprite":
            subtotalrefresco=numero*40
        elif  sabor == "CocaCola":
            subtotalrefresco=numero*45
        
        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel(f"$ {self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero}  Refresco: Sabor {sabor} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarHelado(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidadHelado.GetValue())
        sabor=self.cmbSaborHelado.GetValue()
        if sabor == "Chocochips":
            subtotalhelado=numero*40
        elif sabor == "Chocolate":
            subtotalhelado=numero*45
        elif  sabor == "Quesoconsarzamora":
            subtotalhelado=numero*30
        elif  sabor == "Picafresa":
            subtotalhelado=numero*35
        
        self.subtotalDulceria=self.subtotalDulceria+subtotalhelado
        self.lbSubtotal.SetLabel(f"$ {self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero}  Helado: Sabor {sabor} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def limpiarD(self):
        #Limpiamos las variables de instancia
        self.subtotalDulceria=0
        self.infoDulceria=""

        #Limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboP.SetValue(0)
        self.spComboF.SetValue(0)
        self.spComboY.SetValue(0)
        self.spCantidadPalomitas.SetValue(0)
        self.spCantidadRefresco.SetValue(0)
        self.spCantidadICEE.SetValue(0)
        self.spCantidadHelado.SetValue(0)
        self.cmbSaborHelado.SetSelection(wx.NOT_FOUND)
        self.cmbsaborRefresco.SetSelection(wx.NOT_FOUND)
        self.cmbTamanoPalomitas.SetSelection(wx.NOT_FOUND)
        self.cmbTamanoICEE.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("----")
        self.lbSubtotal.SetLabel("$00.00")    

    def LimpiarTaquilla(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria. \n"
        f"¿Esta seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        f"Subtotal Dulceria: ${self.subtotalDulceria}",
        "Dulceria",style=wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #Cerramos el dialogo

        if respuesta == wx.ID_YES:
            print(f"Venta de Dulceria realizada \n {self.infoDulceria}")
            v4 = Ventana4 (self, informacion=self.infoTaquilla,
                           subtotal1=self.subtotalTaquilla,
                           informacion2=self.infoDulceria,
                           subtotal2=self.subtotalDulceria)
            v4.Show()
            self.limpiarD()
            self.Hide()
        elif respuesta ==wx.ID_NO:
            self.limpiarD()

        event.Skip()

    def cerrarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.Close()
        wx.Exit()
        event.Skip()

# end of class Ventana3

class MyApp(wx.App):
    def OnInit(self):
        self.frame = Ventana3(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
