#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Nov 26 12:20:05 2025
#

import wx

#Siguiente ventana
from cinemovie_v3 import Ventana3

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((872, 867))
        self.SetTitle("Taquilla")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(149, 0, 9))
        self.panel_1.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, ""))

        #Variables de instancia para la Taquilla
        self.subtotalTaquilla=0
        self.informacion=""
        self.horarioseleccionado=""
        self.peliculaseleccionada=""
        self.salaseleccionada=""
        self.cantidadAdultos=0
        self.CantidadMenores=0
        
        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 5, 0, 0)
        grid_sizer_10.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "$90")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_1.Add(label_2, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos Adultos")
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        self.spAdultos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_1.Add(self.spAdultos, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Adultos:$")
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_1.Add(label_9, 0, 0, 0)

        self.lbSubtotalA = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSubtotalA.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_1.Add(self.lbSubtotalA, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 5, 0, 0)
        grid_sizer_3.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "$80")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_9.Add(label_5, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Boleto Niños")
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial Narrow"))
        grid_sizer_9.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        self.spMenores = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_9.Add(self.spMenores, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Menores:$")
        label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        label_10.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_9.Add(label_10, 0, 0, 0)

        self.lbSubtotalM = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSubtotalM.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_9.Add(self.lbSubtotalM, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario")
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(label_7, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala")
        label_8.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(label_8, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.btnPellicula1 = wx.Button(self.panel_1, wx.ID_ANY, "..")
        self.btnPellicula1.SetMinSize((110, 155))
        self.btnPellicula1.SetBitmap(wx.Bitmap("pelicula1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(self.btnPellicula1, 0, 0, 0)

        self.lbPelicula1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Coraline")
        self.lbPelicula1.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_5.Add(self.lbPelicula1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_12 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "9:00 -> 10:00 pm")
        self.rbHorario1.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario1.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_12.Add(self.rbHorario1, 0, wx.ALIGN_BOTTOM, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "11:00 -> 12:40 pm")
        self.rbHorario2.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario2.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_12.Add(self.rbHorario2, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "8:00 -> 9:40 am")
        self.rbHorario3.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario3.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_12.Add(self.rbHorario3, 0, 0, 0)

        self.lbNumsala1 = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbNumsala1.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_5.Add(self.lbNumsala1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_6 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.btnPelicula2 = wx.Button(self.panel_1, wx.ID_ANY, "..")
        self.btnPelicula2.SetMinSize((109, 149))
        self.btnPelicula2.SetBitmap(wx.Bitmap("pelicula2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(self.btnPelicula2, 0, 0, 0)

        self.lbPelicula2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Conjuro 4")
        self.lbPelicula2.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_6.Add(self.lbPelicula2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_13 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_6.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.rbHorario4 = wx.RadioButton(self.panel_1, wx.ID_ANY, "6:00 -> 8:00 am")
        self.rbHorario4.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario4.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_13.Add(self.rbHorario4, 0, 0, 0)

        self.rbHorario5 = wx.RadioButton(self.panel_1, wx.ID_ANY, "2:15 -> 4:30 am")
        self.rbHorario5.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario5.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_13.Add(self.rbHorario5, 0, 0, 0)

        self.rbHorario6 = wx.RadioButton(self.panel_1, wx.ID_ANY, "10:33 -> 12:00 pm")
        self.rbHorario6.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario6.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_13.Add(self.rbHorario6, 0, 0, 0)

        self.lbNumsala2 = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbNumsala2.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_6.Add(self.lbNumsala2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnPelicula3 = wx.Button(self.panel_1, wx.ID_ANY, "..")
        self.btnPelicula3.SetMinSize((110, 132))
        self.btnPelicula3.SetBitmap(wx.Bitmap("prlicula3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnPelicula3, 0, 0, 0)

        self.lbPelicula3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Gato Pardo")
        self.lbPelicula3.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_7.Add(self.lbPelicula3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_14 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_7.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        self.rbHorario7 = wx.RadioButton(self.panel_1, wx.ID_ANY, "10:00 -> 1:00 am")
        self.rbHorario7.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario7.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_14.Add(self.rbHorario7, 0, 0, 0)

        self.rbHorario8 = wx.RadioButton(self.panel_1, wx.ID_ANY, "7:00 ->10:00 am")
        self.rbHorario8.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario8.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_14.Add(self.rbHorario8, 0, 0, 0)

        self.rbHorario9 = wx.RadioButton(self.panel_1, wx.ID_ANY, "1:00 -> 4:00 am")
        self.rbHorario9.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario9.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_14.Add(self.rbHorario9, 0, 0, 0)

        self.lbNumsala3 = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbNumsala3.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_7.Add(self.lbNumsala3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_8 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.btnPelicula4 = wx.Button(self.panel_1, wx.ID_ANY, "..")
        self.btnPelicula4.SetMinSize((109, 141))
        self.btnPelicula4.SetBitmap(wx.Bitmap("pelicula4.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(self.btnPelicula4, 0, 0, 0)

        self.lbPelicula4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chuky")
        self.lbPelicula4.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_8.Add(self.lbPelicula4, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_15 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.rbHorario10 = wx.RadioButton(self.panel_1, wx.ID_ANY, "4:00 -> 6:00 pm ")
        self.rbHorario10.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario10.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_15.Add(self.rbHorario10, 0, 0, 0)

        self.rbHorario11 = wx.RadioButton(self.panel_1, wx.ID_ANY, "10:00 -> 12:00 am")
        self.rbHorario11.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario11.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_15.Add(self.rbHorario11, 0, 0, 0)

        self.rbHorario12 = wx.RadioButton(self.panel_1, wx.ID_ANY, "5:00 -> 7:00 pm")
        self.rbHorario12.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario12.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_15.Add(self.rbHorario12, 0, 0, 0)

        self.lbNumsala4 = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbNumsala4.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_8.Add(self.lbNumsala4, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_11 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetBitmap(wx.Bitmap("LogoVolver.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(self.btnLimpiar, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetForegroundColour(wx.Colour(9, 9, 9))
        self.btnSiguiente.SetBitmap(wx.Bitmap("ImagenSiguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        grid_sizer_11.Add(self.btnSalir, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_13.AddGrowableRow(2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spAdultos.Bind(wx.EVT_SPINCTRL, self.calcularBoletoAdultos)
        self.spMenores.Bind(wx.EVT_SPINCTRL, self.calcularBoletoMenores)
        self.btnPellicula1.Bind(wx.EVT_BUTTON, self.SeleccionarPelicula1)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.btnPelicula2.Bind(wx.EVT_BUTTON, self.SeleccionarPelicula2)
        self.rbHorario4.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario4)
        self.rbHorario5.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario5)
        self.rbHorario6.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario6)
        self.btnPelicula3.Bind(wx.EVT_BUTTON, self.SeleccionarPelicula3)
        self.rbHorario7.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario7)
        self.rbHorario8.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario8)
        self.rbHorario9.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario9)
        self.btnPelicula4.Bind(wx.EVT_BUTTON, self.SeleccionarPelicula4)
        self.rbHorario10.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario10)
        self.rbHorario11.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario11)
        self.rbHorario12.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario12)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarVentana)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrarVentana)
        # end wxGlade

    def calcularBoletoAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        numero=int(self.spAdultos.GetValue())
        self.cantidadAdultos=numero
        SubtotalAdulto=numero*90
        self.subtotalAdulto=SubtotalAdulto
        self.lbSubtotalA.SetLabel(f"${self.subtotalAdulto}")
        print(f"Boletos Adultos {numero} \n Subtotal${SubtotalAdulto}")
        self.actualizarSubtotalTotal()
        event.Skip()

    def calcularBoletoMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        numero=int(self.spMenores.GetValue())
        self.CantidadMenores=numero
        SubtotalMenores=numero*80
        self.subtotalmenores=SubtotalMenores
        self.lbSubtotalM.SetLabel(f"${SubtotalMenores}")
        print(f"Boletos Menores {numero} \n Subtotal${SubtotalMenores}")
        self.actualizarSubtotalTotal()
        event.Skip()

    def actualizarSubtotalTotal(self):
        subtotalA = getattr(self, 'subtotalAdulto', 0)
        subtotalM = getattr(self, 'subtotalmenores', 0) 
        self.subtotalTaquilla = subtotalA + subtotalM
        print(f"Subtotal de Taquilla Actualizado: ${self.subtotalTaquilla}")
        

    def SeleccionarPelicula1(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.lbPelicula1.GetLabelText()
        self.lbNumsala1.SetLabel("1")
        self.peliculaseleccionada=pelicula
        self.salaseleccionada=self.lbNumsala1.GetLabelText()
        print(f"Pelicula Seleccionada {pelicula} " )
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario1.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario2.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario3.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def SeleccionarPelicula2(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.lbPelicula2.GetLabelText()
        sala=self.lbNumsala2.SetLabel("2")
        self.peliculaseleccionada=pelicula
        self.salaseleccionada=self.lbNumsala2.GetLabelText()
        print(f"Pelicula Seleccionada {pelicula}" )
        event.Skip()

    def seleccionHorario4(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario4.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario5(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario5.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario6(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario6.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def SeleccionarPelicula3(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.lbPelicula3.GetLabelText()
        self.lbNumsala3.SetLabel("3")
        self.peliculaseleccionada=pelicula
        self.salaseleccionada=self.lbNumsala3.GetLabelText()
        print(f"Pelicula Seleccionada {pelicula} " )
        event.Skip()

    def seleccionHorario7(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario7.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario8(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario8.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario9(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario9.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def SeleccionarPelicula4(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.lbPelicula4.GetLabelText()
        self.lbNumsala4.SetLabel("4")
        self.peliculaseleccionada=pelicula
        self.salaseleccionada=self.lbNumsala4.GetLabelText()
        print(f"Pelicula Seleccionada {pelicula} " )
        event.Skip()

    def seleccionHorario10(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario10.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario11(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario11.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def seleccionHorario12(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioseleccionado=self.rbHorario12.GetLabelText()
        print(f"Horario: {self.horarioseleccionado}")
        event.Skip()

    def limpiarVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Pelicula: {self.peliculaseleccionada} \n Horario {self.horarioseleccionado} \n Sala: {self.salaseleccionada}" 
        self.informacion = f"{self.informacion} \n Total de Adultos$: {self.subtotalAdulto} \n Cantidad Adultos: {self.cantidadAdultos} \n Total de Menores$: {self.subtotalmenores} \n Cantidad Menores: {self.CantidadMenores} " 
        self.informacion = f"{self.informacion} \n Subtotal: {self.subtotalTaquilla}"

        pregunta=wx.MessageDialog(self, f"Confirmacion de Taquilla. \n "
                                  f"Esta seguro que desea adquirir\n\n {self.informacion}", 
                                  "Taquilla", style=wx.YES_NO | wx.ICON_QUESTION) 
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print(f"Venta de Taquilla realizada\n {self.informacion}")
            v3=Ventana3(self, informacion=self.informacion, subtotal1=self.subtotalTaquilla)
            v3.Show()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

    def limpiarValores_Campos(self):

        #Limpiar variables de instancia de la Taquilla
        self.subtotalTaquilla=0
        self.informacion=""
        self.horarioseleccionado=""
        self.peliculaseleccionada=""
        self.salaseleccionada=""
        self.cantidadAdultos=0
        self.CantidadMenores=0

        #Limpiar Campos
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.rbHorario4.SetValue(False)
        self.rbHorario5.SetValue(False)
        self.rbHorario6.SetValue(False)
        self.rbHorario7.SetValue(False)
        self.rbHorario8.SetValue(False)
        self.rbHorario9.SetValue(False)
        self.rbHorario10.SetValue(False)
        self.rbHorario11.SetValue(False)
        self.rbHorario12.SetValue(False)
        self.lbNumsala1.SetLabel("---")
        self.lbNumsala2.SetLabel("---")
        self.lbNumsala3.SetLabel("---")
        self.lbNumsala4.SetLabel("---")
        self.spAdultos.SetValue("0")
        self.spMenores.SetValue("0")
        self.lbSubtotalA.SetLabel("0")
        self.lbSubtotalM.SetLabel("0")

    def cerrarVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.Close()
        event.Skip()

# end of class Ventana2

class MyAppCineMovie(wx.App):
    def OnInit(self):
        self.frame = Ventana2(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCineMovie

if __name__ == "__main__":
    appCineMovie = MyAppCineMovie(0)
    appCineMovie.MainLoop()
