#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Tue Oct 28 07:57:55 2025
#

import wx

#Siguiente ventana
from cineMovie_v22 import Ventana2

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((609, 520))
        self.SetTitle("Inicio de Sesion -CineMovie")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(149, 0, 9))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Inicio de Sesion")
        lbTitulo.SetForegroundColour(wx.Colour(255, 255, 255))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_1.Add(lbTitulo, 0, wx.ALIGN_CENTER, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:")
        lbUsuario.SetMinSize((89, 30))
        lbUsuario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbUsuario.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_2.Add(lbUsuario, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_2.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Clave:")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(22, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(self.tfClave, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((160, 30))
        self.btnSiguiente.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.btnSiguiente.SetBitmap(wx.Bitmap("ImagenSiguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((160, 30))
        self.btnSalir.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSalir.SetBitmap(wx.Bitmap("LogoVolver.png", wx.BITMAP_TYPE_ANY), dir=wx.RIGHT)
        grid_sizer_4.Add(self.btnSalir, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre =self.tfUsuario.GetValue ( )
        clave = self.tfClave.GetValue ( )

        if nombre == "Eyma" and clave == "5679":
            print(f"Bienvenidos al sistema. Acceso Autorizado")
            v2 =Ventana2(self)
            v2.Show()
            self.Hide()
            

        else:
            print("Acceso denegado. Usuario o clave incorrectos. ")



        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cerrara la ventana. \n " 
        "Esta seguro que desea salir?", "Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION) 

        respuesta = pregunta.ShowModal ()
        pregunta.Destroy() #Cerramos el dialogo

        if respuesta ==wx.ID_YES:
            print("Bye!")
            self.Close() #Cierra la ventana

        event.Skip()

# end of class Ventana1

class MyAppCineMovie(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCineMovie

if __name__ == "__main__":
    appCineMovie = MyAppCineMovie(0)
    appCineMovie.MainLoop()
